### ISSUE TITLE
前端架构 - 了解React  ［进行中］

### ISSUE THREAD

**Issue by itang** [itang/todo.itang.me#30]
## TODO
- [ ] 与Ractive.js 比较
## 资料
- [ ] http://facebook.github.io/react/index.html
- [ ] https://github.com/facebook/flux
## React 组件库
- [ ] http://react-bootstrap.github.io/components.html
- [ ] http://react-components.com/
## 工具篇
- [ ] http://colobu.com/2014/08/29/modern-web-development-tools/
